# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 00:45
from __future__ import unicode_literals

from django.db import migrations


def copy_src_to_dst(Source, Destination):
    for src in Source.objects.all():
        dst = Destination(
            title=src.title,
            start=src.start,
            description=src.description,
            slots=src.slots
        )
        dst.save()
        dst.speakers.set(src.speakers.all())
        src.delete()


def forward_course_abc_to_mti(apps, schema_editor):
    """
    para cada ABC(old), instanciar um MTI(new) com todos os atributos
    salvar o MTI
    associar os speakers do ABC ao MTI
    deletar o ABC
    """
    copy_src_to_dst(
        apps.get_model('core', 'CourseOld'),
        apps.get_model('core', 'Course')
    )


def backward_course_abc_to_mti(apps, schema_editor):
    """
    para cada MTI(new), instanciar um ABC(old) com todos os atributos
    salvar o ABC
    associar os speakers do MTI ao ABC
    deletar o MTI
    """
    copy_src_to_dst(
        apps.get_model('core', 'Course'),
        apps.get_model('core', 'CourseOld')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_course'),
    ]

    operations = [
        migrations.RunPython(forward_course_abc_to_mti,
                             backward_course_abc_to_mti)
    ]
